Repository SpartaNBTTeam/newsfeed, pull requests merged in 2024-06, with the labels that each got.

#3 feat: 초기설정
  .eslintrc.cjs
  .gitignore
  .prettierrc
  .yarn/install-state.gz
  .yarn/releases/yarn-4.2.2.cjs
  .yarnrc.yml
  index.html
  package.json
  src/App.jsx
  src/components/Layout.jsx
  src/main.jsx
  src/pages/home/Home.jsx
  src/pages/home/index.js
  src/pages/index.js
  src/redux/config/configStore.js
  src/redux/slices/feedsSlices.js
  src/redux/slices/userSlices.js
  src/router/Router.jsx
  src/styles/GlobalStyles.js
  src/styles/constants.js
  src/supabase/supabaseClient.js
  vite.config.js
  yarn.lock
Labels: enhancement

#6 feat: import order 규칙 설정
  .eslintrc.cjs
  .yarn/install-state.gz
  jsconfig.json
  package.json
  src/App.jsx
  src/main.jsx
  src/redux/config/configStore.js
  src/router/Router.jsx
  vite.config.js
  yarn.lock
Labels: enhancement

#7 feat: 버튼 시스템 컴포넌트 추가
  src/components/Button.jsx
  src/styles/constants.js
  src/styles/utils.js
Labels: enhancement

#9 feat: 헤더, 사이드바 공용 레이아웃 추가
  src/assets/images/common/pencil.png
  src/assets/images/common/user.png
  src/components/Layout.jsx
  src/components/Layout/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/ProfileSidebar.jsx
  src/components/Layout/index.js
  src/pages/home/Home.jsx
  src/router/Router.jsx
  src/styles/GlobalStyles.js
  src/styles/colors.js
  src/styles/constants.js
  src/styles/utils.js
Labels: enhancement

#10 feat: UI 문서화를 위한 스토리북 도입
  .eslintrc.cjs
  .gitignore
  .storybook/main.js
  .storybook/preview.jsx
  .yarn/install-state.gz
  package.json
  src/components/Button/Button.jsx
  src/components/Button/Button.stories.jsx
  src/components/Button/index.js
  src/components/Header/Header.jsx
  src/components/Header/Header.stories.jsx
  src/components/Header/index.js
  src/components/Layout/Layout.jsx
  src/components/Layout/index.js
  src/router/Router.jsx
  yarn.lock
Labels: enhancement

#11 fix: 폴더 대소문자 구분 / gitignore에 storebook 추가
  .gitignore
  src/pages/Home/Home.jsx
  src/pages/Home/index.js
Labels: bug

#13 chore: 0.0.1
  .eslintrc.cjs
  .gitignore
  .prettierrc
  .storybook/main.js
  .storybook/preview.jsx
  .yarn/install-state.gz
  .yarn/releases/yarn-4.2.2.cjs
  .yarnrc.yml
  index.html
  jsconfig.json
  package.json
  src/App.jsx
  src/assets/images/common/pencil.png
  src/assets/images/common/user.png
  src/components/Button/Button.jsx
  src/components/Button/Button.stories.jsx
  src/components/Button/index.js
  src/components/Header/Header.jsx
  src/components/Header/Header.stories.jsx
  src/components/Header/index.js
  src/components/Layout/Layout.jsx
  src/components/Layout/ProfileSidebar.jsx
  src/components/Layout/index.js
  src/main.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/index.js
  src/pages/home/Home.jsx
  src/pages/home/index.js
  src/pages/index.js
  src/redux/config/configStore.js
  src/redux/slices/feedsSlices.js
  src/redux/slices/userSlices.js
  src/router/Router.jsx
  src/styles/GlobalStyles.js
  src/styles/colors.js
  src/styles/constants.js
  src/styles/utils.js
  src/supabase/supabaseClient.js
  vite.config.js
  yarn.lock
Labels: enhancement

#14 feat: 타이포그라피 컴포넌트 추가
  src/components/Button/Button.jsx
  src/components/Button/Button.stories.jsx
  src/components/Header/Header.stories.jsx
  src/components/Typography/Typography.jsx
  src/components/Typography/Typography.stories.jsx
Labels: enhancement

#18 chore: 0.0.2
  src/components/Button/Button.jsx
  src/components/Button/Button.stories.jsx
  src/components/Header/Header.stories.jsx
  src/components/Typography/Typography.jsx
  src/components/Typography/Typography.stories.jsx
Labels: enhancement

#19 fix: 소문자 디렉토리 홈 강제 삭제
  src/pages/home/Home.jsx
  src/pages/home/index.js
Labels: bug

#20 chore: 0.0.3
  src/pages/home/Home.jsx
  src/pages/home/index.js
Labels: bug

#25 style: 스타일드 컴포넌트 이름 변경 및 import 오류 수정
  src/components/Button/Button.jsx
  src/components/Header/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/ProfileSidebar.jsx
  src/components/Typography/Typography.jsx
  src/components/Typography/index.js
Labels: enhancement

#26 feat: 프로필페이지 tabs 컴포넌트 추가
  src/components/Button/Button.stories.jsx
  src/components/ProfileTabs.jsx
  src/components/Tabs/Tabs.jsx
  src/components/Tabs/Tabs.stories.jsx
  src/components/Tabs/index.js
  src/components/Typography/Typography.stories.jsx
  src/pages/Favorites/Favorites.jsx
  src/pages/Favorites/index.js
  src/pages/Profile/Profile.jsx
  src/pages/Profile/index.js
  src/pages/index.js
  src/router/Router.jsx
Labels: enhancement

#27 chore:0.0.4
  src/components/Button/Button.jsx
  src/components/Button/Button.stories.jsx
  src/components/Header/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/ProfileSidebar.jsx
  src/components/ProfileTabs.jsx
  src/components/Tabs/Tabs.jsx
  src/components/Tabs/Tabs.stories.jsx
  src/components/Tabs/index.js
  src/components/Typography/Typography.jsx
  src/components/Typography/Typography.stories.jsx
  src/components/Typography/index.js
  src/pages/Favorites/Favorites.jsx
  src/pages/Favorites/index.js
  src/pages/Profile/Profile.jsx
  src/pages/Profile/index.js
  src/pages/index.js
  src/router/Router.jsx
Labels: enhancement

#24 feat: main 목업
  .yarn/install-state.gz
  src/assets/images/common/ic_general_like.svg
  src/assets/images/common/ic_general_like_fill.svg
  src/components/Card/Card.jsx
  src/components/Card/index.js
  src/pages/Home/Home.jsx
  src/pages/Home/SectionHeader.jsx
Labels: enhancement

#31 feat: 회원가입 로그인 페이지 구현
  .yarn/install-state.gz
  package.json
  src/App.jsx
  src/assets/icons/ic_general_eye.svg
  src/assets/icons/ic_general_eye_off.svg
  src/assets/images/common/pencil.png
  src/components/AuthHeader.jsx
  src/components/Header/Header.jsx
  src/components/Header/HeaderButtons.jsx
  src/components/Input/Input.jsx
  src/components/Input/PasswordInput.jsx
  src/components/Input/index.js
  src/components/Layout/Layout.jsx
  src/components/Layout/ProfileSidebar.jsx
  src/components/Layout/commonLoader.js
  src/components/ProfileSideBar/GuestProfile.jsx
  src/components/ProfileSideBar/ProfileSideBar.jsx
  src/components/ProfileSideBar/UserProfile.jsx
  src/components/ProfileSideBar/index.js
  src/components/ProfileSideBar/styles.js
  src/components/ProfileTabs.jsx
  src/components/ProtectedRoute.jsx
  src/hooks/useShallowEqualSelector.jsx
  src/pages/Signin/Signin.jsx
  src/pages/Signin/index.js
  src/pages/Signup/Signup.jsx
  src/pages/Signup/index.js
  src/pages/index.js
  src/redux/auth/authError.js
  src/redux/auth/authServices.js
  src/redux/auth/authSlices.js
  src/redux/auth/authThunk.js
  src/redux/config/configStore.js
  src/redux/slices/userSlices.js
  src/router/Router.jsx
  src/svg/index.js
  vite.config.js
  yarn.lock
Labels: enhancement

#32 feat: main card supabase 연결
  src/components/Card/Card.jsx
  src/pages/Home/Home.jsx
Labels: enhancement

#29 feat: 상세페이지 댓글 작성 삭제 구현
  .eslintrc.cjs
  src/assets/images/common/detail/bookMarkOn.svg
  src/assets/images/common/detail/bookmark.svg
  src/assets/images/common/detail/share.svg
  src/pages/Detail/Comment.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Retouch.jsx
  src/pages/Detail/index.js
  src/pages/index.js
  src/router/Router.jsx
Labels: enhancement

#33 feat: 작성폼 기능 구현
  .yarn/install-state.gz
  package.json
  src/assets/icons/ic_general_like.svg
  src/assets/icons/ic_general_like_fill.svg
  src/assets/icons/ic_general_pencil_fill.svg
  src/assets/icons/ic_general_share.svg
  src/assets/icons/ic_general_trash_can.svg
  src/assets/images/common/detail/bookMarkOn.svg
  src/assets/images/common/detail/bookmark.svg
  src/components/Card/Card.jsx
  src/components/Header/AuthHeader.jsx
  src/components/Header/HeaderButtons.jsx
  src/components/Header/index.js
  src/components/Layout/Layout.jsx
  src/components/NoFeeds.jsx
  src/components/ProfileSideBar/GuestProfile.jsx
  src/components/ProfileSideBar/ProfileSideBar.jsx
  src/components/ProfileSideBar/UserProfile.jsx
  src/components/ProfileSideBar/index.js
  src/components/ProfileSideBar/styles.js
  src/hooks/useIsLoginUser.jsx
  src/loader/authLoader.js
  src/loader/commonLoader.js
  src/loader/detailLoader.js
  src/loader/homeLoader.js
  src/main.jsx
  src/pages/Detail/Comment.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Retouch.jsx
  src/pages/Editor/Editor.jsx
  src/pages/Editor/EditorHeader.jsx
  src/pages/Editor/index.js
  src/pages/Editor/newEditorLoader.js
  src/pages/Editor/toastUiImports.js
  src/pages/Home/Home.jsx
  src/pages/Signin/Signin.jsx
  src/pages/Signup/Signup.jsx
  src/pages/index.js
  src/redux/_config/configStore.js
  src/redux/comments/commentThunk.js
  src/redux/comments/commentsServices.js
  src/redux/comments/commentsSlices.js
  src/redux/feeds/feedsServices.js
  src/redux/feeds/feedsSlices.js
  src/redux/feeds/feedsThunk.js
  src/redux/slices/feedsSlices.js
  src/router/Router.jsx
  src/supabase/supabaseClient.js
  src/svg/index.js
  src/utils/copyURLToClipboard.js
  src/utils/index.js
  yarn.lock
Labels: enhancement

#37 feat: 프로필 수정 페이지 연동
  .yarn/install-state.gz
  src/components/ProfileSideBar/UserProfile.jsx
  src/components/ProfileSideBar/styles.js
  src/pages/EditProfile/EditProfile.jsx
  src/pages/EditProfile/index.js
  src/pages/Home/index.js
  src/pages/index.js
  src/redux/auth/authServices.js
  src/redux/auth/authSlices.js
  src/redux/auth/authThunk.js
  src/router/Router.jsx
Labels: enhancement

#38 chore: 0.0.5
  .yarn/install-state.gz
  src/components/ProfileSideBar/UserProfile.jsx
  src/components/ProfileSideBar/index.js
  src/components/ProfileSideBar/styles.js
  src/pages/Detail/Comment.jsx
  src/pages/Detail/Detail.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/EditProfile/index.js
  src/pages/Home/index.js
  src/pages/index.js
  src/redux/auth/authServices.js
  src/redux/auth/authSlices.js
  src/redux/auth/authThunk.js
  src/router/Router.jsx
Labels: enhancement

#39 feat: 마이페이지 적용 및 로딩바 구현
  index.html
  src/components/Card/Card.jsx
  src/components/Loader.jsx
  src/components/ProfileTabs.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Favorites/Favorites.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/index.js
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/index.js
  src/pages/Profile/Profile.jsx
  src/pages/index.js
  src/redux/auth/authThunk.js
  src/router/Router.jsx
Labels: enhancement

#40 chore: 1.0.0
  index.html
  src/components/Card/Card.jsx
  src/components/Loader.jsx
  src/components/ProfileTabs.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Favorites/Favorites.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/index.js
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/index.js
  src/pages/Profile/Profile.jsx
  src/pages/index.js
  src/redux/auth/authThunk.js
  src/router/Router.jsx
Labels: enhancement

#41 fix: 디펜던시 제거
  src/components/Card/Card.jsx
Labels: bug

#42 chore: 1.0.1
  src/components/Card/Card.jsx
Labels: bug

#44 fix: 오류 수정
  src/pages/Detail/Comment.jsx
Labels: bug

#46 chore: 1.0.3
  src/components/ProfileSideBar/UserProfile.jsx
  src/pages/EditProfile/EditProfile.jsx
Labels: enhancement

#48 feat: 프로필 이미지 업로드기능 추가
  src/components/AvatarEditUI.jsx
  src/components/Card/Card.jsx
  src/components/ProfileSideBar/UserProfile.jsx
  src/components/ProfileSideBar/styles.js
  src/pages/Detail/Comment.jsx
  src/pages/Detail/Detail.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/Home/SectionHeader.jsx
  src/redux/auth/authServices.js
Labels: enhancement

#50 chore: 1.1.1
  src/pages/EditProfile/EditProfile.jsx
  src/pages/Home/SectionHeader.jsx
Labels: bug

#51 refactor: readme 수정
  README.md
  src/pages/Detail/Comment.jsx
Labels: documentation

#52 chore: 1.1.2
  README.md
  src/pages/Detail/Comment.jsx
Labels: documentation

#53 refactor: 리드미 수정
  README.md
Labels: documentation

#54 chore: 1.1.3
  README.md
Labels: documentation

#55 feat: workflow 생성
  .github/workflows/deploy.yml
Labels: documentation

#57 fix: workflow 에러 수정
  .github/workflows/deploy.yml
Labels: bug

#59 fix: workflow-error2
  .github/workflows/deploy.yml
Labels: bug

#61 fix: remove-node-version
  .github/workflows/deploy.yml
Labels: bug

#67 fix: workflow-error
  .github/workflows/deploy.yml
Labels: bug
